spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/rewards_db
    username: postgres
    password: root
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

