server:
  port: 8068

server:
  port: 8068

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/transaction_db
    username: postgres
    password: root
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

